hdfs dfs -mkdir /user/hive/warehouse/dcd.db/cmr_fran/Base_credito_19_04

hdfs dfs -copyFromLocal /home/fgastardi/TABELA_5KK_VAR_CREDITO_FRAN.txt /user/hive/warehouse/dcd.db/cmr_fran/Base_credito_19_04/TABELA_5KK_VAR_CREDITO_FRAN.txt

create external table tabela_5kk_var_credito_fran_1 (
cd_cnpj_contraparte string,
dt_base string,
in_default_basileia_2_mes string,
pc_utlz_chq_lim_glob_mes string,
pc_utlz_cartao_mes string,
pc_utlz_ctagarantida_mes string,
in_cheque_especial string,
in_credito_pessoal string,
in_aquisicao_bens string,
in_cdcveic_leasing string,
in_financ_imobiliario string,
in_cartao_credito string,
in_financ_cartao_credito string,
in_renegociacao string,
in_desconto string,
in_adiantamento_depositante string,
in_capital_giro string,
in_conta_garantida string,
in_rural string,
in_finame_bndes string,
c_dt_base_saldo_maximo string,
c_vr_saldo_maximo string,
c_dt_base_inicio string,
c_dt_base_fim string,
qt_meses_risc_36m string,
c_vr_saldo_medio string,
qt_default_36m string,
dt_ultimo_default string,
pc_utlz_chq_lim_glob_36m string,
pc_utlz_chq_lim_glob_12m_exp string,
qt_utlz_chq_lim_glob_mes string,
qt_utlz_chq_lim_glob_36m string,
qt_utlz_chq_lim_glob_12m string,
qt_meses_possui_chq_lim_glob_36m string,
qt_meses_possui_chq_lim_glob_12m string,
pc_a_utilizar_compr_chq_lim_glob string,
pc_utlz_cartao_36m string,
pc_utlz_cartao_12m_exp string,
qt_utlz_cartao_mes string,
qt_utlz_cartao_36m string,
qt_utlz_cartao_12m string,
qt_meses_possui_cartao_36m string,
qt_meses_possui_cartao_12m string,
pc_a_utilizar_compr_cartao string,
pc_utlz_ctagarantida_36m string,
pc_utlz_ctagarantida_12m_exp string,
qt_utlz_ctagarantida_mes string,
qt_utlz_ctagarantida_36m string,
qt_utlz_ctagarantida_12m string,
qt_meses_possui_ctagarantida_36m string,
qt_meses_possui_ctagarantida_12m string,
pc_a_utilizar_compr_ctagarant string,
c_vr_saldo_maximo_sm string,
c_vr_saldo_medio_sm string,
qt_dt_base_fim_12m string,
qt_dt_base_inicio_12m string,
qt_dt_base_saldo_maximo_12m string,
qt_dt_base_def_12m string,
qt_default_12m string,
qt_rtrit_hist_prim string,
qt_rtrit_hist string,
cd_possui_restr_historico string)
row format delimited
fields terminated by '\|'
location '/user/hive/warehouse/dcd.db/cmr_fran/Base_credito_19_04';


#Eliminar a primeira linha da tabela 
create table tabela_5kk_var_credito_fran as
select cd_cnpj_contraparte,
dt_base,
in_default_basileia_2_mes,
cast(pc_utlz_chq_lim_glob_mes as float) as pc_utlz_chq_lim_glob_mes,
cast(pc_utlz_cartao_mes as float) as pc_utlz_cartao_mes,
cast(pc_utlz_ctagarantida_mes as float) as pc_utlz_ctagarantida_mes,
cast(in_cheque_especial as int) as in_cheque_especial,
cast(in_credito_pessoal as int) as in_credito_pessoal,
cast(in_aquisicao_bens as int) as in_aquisicao_bens,
cast(in_cdcveic_leasing as int) as in_cdcveic_leasing,
cast(in_financ_imobiliario as int) as in_financ_imobiliario,
cast(in_cartao_credito as int) as in_cartao_credito,
cast(in_financ_cartao_credito as int) as in_financ_cartao_credito,
cast(in_renegociacao as int) as in_renegociacao,
cast(in_desconto as int) as in_desconto,
cast(in_adiantamento_depositante as int) as in_adiantamento_depositante,
cast(in_capital_giro as int) as in_capital_giro,
cast(in_conta_garantida as int) as in_conta_garantida,
cast(in_rural as int) as in_rural,
cast(in_finame_bndes as int) as in_finame_bndes,
c_dt_base_saldo_maximo,
cast(c_vr_saldo_maximo as float) as c_vr_saldo_maximo,
c_dt_base_inicio,
c_dt_base_fim,
cast(qt_meses_risc_36m as float) as qt_meses_risc_36m,
cast(c_vr_saldo_medio as float) as c_vr_saldo_medio,
cast(qt_default_36m as float) as qt_default_36m,
dt_ultimo_default,
cast(pc_utlz_chq_lim_glob_36m as float) as pc_utlz_chq_lim_glob_36m,
cast(pc_utlz_chq_lim_glob_12m_exp as float) as pc_utlz_chq_lim_glob_12m_exp,
cast(qt_utlz_chq_lim_glob_mes as float) as qt_utlz_chq_lim_glob_mes,
cast(qt_utlz_chq_lim_glob_36m as float) as qt_utlz_chq_lim_glob_36m,
cast(qt_utlz_chq_lim_glob_12m as float) as qt_utlz_chq_lim_glob_12m,
cast(qt_meses_possui_chq_lim_glob_36m as float) as qt_meses_possui_chq_lim_glob_36m,
cast(qt_meses_possui_chq_lim_glob_12m as float) as qt_meses_possui_chq_lim_glob_12m,
cast(pc_a_utilizar_compr_chq_lim_glob as float) as pc_a_utilizar_compr_chq_lim_glob,
cast(pc_utlz_cartao_36m as float) as pc_utlz_cartao_36m,
cast(pc_utlz_cartao_12m_exp as float) as pc_utlz_cartao_12m_exp,
cast(qt_utlz_cartao_mes as float) as qt_utlz_cartao_mes,
cast(qt_utlz_cartao_36m as float) as qt_utlz_cartao_36m,
cast(qt_utlz_cartao_12m as float) as qt_utlz_cartao_12m,
cast(qt_meses_possui_cartao_36m as float) as qt_meses_possui_cartao_36m,
cast(qt_meses_possui_cartao_12m as float) as qt_meses_possui_cartao_12m,
cast(pc_a_utilizar_compr_cartao as float) as pc_a_utilizar_compr_cartao,
cast(pc_utlz_ctagarantida_36m as float) as pc_utlz_ctagarantida_36m,
cast(pc_utlz_ctagarantida_12m_exp as float) as pc_utlz_ctagarantida_12m_exp,
cast(qt_utlz_ctagarantida_mes as float) as qt_utlz_ctagarantida_mes,
cast(qt_utlz_ctagarantida_36m as float) as qt_utlz_ctagarantida_36m,
cast(qt_utlz_ctagarantida_12m as float) as qt_utlz_ctagarantida_12m,
cast(qt_meses_possui_ctagarantida_36m as float) as qt_meses_possui_ctagarantida_36m,
cast(qt_meses_possui_ctagarantida_12m as float) as qt_meses_possui_ctagarantida_12m,
cast(pc_a_utilizar_compr_ctagarant as float) as pc_a_utilizar_compr_ctagarant,
cast(c_vr_saldo_maximo_sm as float) as c_vr_saldo_maximo_sm,
cast(c_vr_saldo_medio_sm as float) as c_vr_saldo_medio_sm,
cast(qt_dt_base_fim_12m as float) as qt_dt_base_fim_12m,
cast(qt_dt_base_inicio_12m as float) as qt_dt_base_inicio_12m,
cast(qt_dt_base_saldo_maximo_12m as float) as qt_dt_base_saldo_maximo_12m,
cast(qt_dt_base_def_12m as float) as qt_dt_base_def_12m,
cast(qt_default_12m as float) as qt_default_12m,
cast(qt_rtrit_hist_prim as float) as qt_rtrit_hist_prim,
cast(qt_rtrit_hist as float) as qt_rtrit_hist,
cast(cd_possui_restr_historico as int) as cd_possui_restr_historico
from tabela_5kk_var_credito_fran_1 where cd_cnpj_contraparte != "CD_CNPJ_CONTRAPARTE";


create table tabela_5kk_var_credito_fran_2 as
select A.*, B.cpf11
from tabela_5kk_var_credito_fran as A left join
5kk_sample_cmr_nao_elegiveis_clientes_201709 as B
on A.cd_cnpj_contraparte = B.cd_cnpj_contraparte;
